ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
