kube-prometheus-stack:
  # NOTE: These must be set manually to the control plane IP addresses
  kubeEtcd:
    endpoints:
      - 95.217.162.47
      - 65.109.238.208
      - 135.181.44.201
  kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager
  kubeScheduler:
    service:
      selector:
        k8s-app: kube-scheduler
  alertmanager:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "tunnel.2411.house"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - alert-manager.2411.house
    alertmanagerspec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  prometheus:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: "tunnel.2411.house"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - prom.2411.house
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
  grafana:
    enabled: false
    forceDeployDatasources: true
    forceDeployDashboards: true
