apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-watchdog
  namespace: network-watchdog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-watchdog
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-watchdog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-watchdog
subjects:
- kind: ServiceAccount
  name: network-watchdog
  namespace: network-watchdog
