teslamate:
  image:
    repository: teslamate/teslamate
    tag: &teslamateTag "3.0.0"
  timeZone: America/Los_Angeles

  virtualHost: teslamate.2411.house

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "tunnel.2411.house"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - &host teslamate.2411.house
    tls:
      - secretName: teslamate-tls-secret
        hosts:
          - *host

  # Use external CNPG PostgreSQL cluster
  remotePostgresql:
    enabled: true
    host: teslamate-pg-rw
    database: teslamate

  # Load CNPG secret and alias keys to what TeslaMate expects
  envFromSecrets:
    - name: teslamate-pg-app
    - name: teslamate-encryption-key

  env:
    DATABASE_USER: "$(username)"
    DATABASE_PASS: "$(password)"

  grafana:
    env:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    envFromSecret: teslamate-pg-app
    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          - name: TeslaMate
            orgId: 1
        datasources:
          - name: TeslaMate
            isDefault: true
            type: postgres
            url: teslamate-pg-ro:5432
            database: teslamate
            user: $__env{username}
            secureJsonData:
              password: $__env{password}
            jsonData:
              sslmode: disable
              postgresVersion: 1800
    image:
      repository: teslamate/grafana
      tag: *teslamateTag
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "tunnel.2411.house"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - &grafanaHost teslagraph.2411.house
      tls:
        - secretName: teslagraph-tls-secret
          hosts:
            - *grafanaHost