apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/MainPool/BigTank/Frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nas-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: frigate-media
  resources:
    requests:
      storage: 1Ti
