apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3-ds
spec:
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["iperf3", "-s"]
        ports:
        - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-tailscale
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: iperf3
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201
