apiVersion: v1
kind: Service
metadata:
  name: paperless-tailscale
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/name: paperless-ngx
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
