gha-runner-scale-set:
  githubConfigUrl: https://github.com/ograff/new_dotfiles
  githubConfigSecret: arc-runners-github
  runnerScaleSetName: homelab
  minRunners: 0
  maxRunners: 5
  containerMode:
    type: kubernetes-novolume
  controllerServiceAccount:
    namespace: arc-controller
    name: arc-controller-gha-rs-controller
