apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: teslamate-pg
  namespace: teslamate
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  instances: 3
  affinity:
    enablePodAntiAffinity: true #default value
    topologyKey: kubernetes.io/hostname #defaul value
    podAntiAffinityType: preferred #default value
    nodeSelector:
      storage: "true"

  storage:
    size: 8Gi
    storageClass: local-single

  bootstrap:
    initdb:
      database: teslamate
      owner: teslamate

  enableSuperuserAccess: true

  monitoring:
    enablePodMonitor: true

  primaryUpdateStrategy: unsupervised
