apiVersion: v1
kind: Secret
metadata:
  name: teslamate-db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_USER: {{ index (lookup "v1" "Secret" .Release.Namespace "teslamate-pg-app").data "username" | b64dec | quote }}
  DATABASE_PASS: {{ index (lookup "v1" "Secret" .Release.Namespace "teslamate-pg-app").data "password" | b64dec | quote }}
