{{- $cnpgSecret := (lookup "v1" "Secret" .Release.Namespace "teslamate-pg-app") }}
{{- if $cnpgSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: teslamate-db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_USER: {{ index $cnpgSecret.data "username" }}
  DATABASE_PASS: {{ index $cnpgSecret.data "password" }}
{{- end }}
