longhorn:
  # Default values for longhorn.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  persistence:
    # -- Replica count of the default Longhorn StorageClass.
    defaultClassReplicaCount: 2
    # -- Data locality of the default Longhorn StorageClass. (Options: "disabled", "best-effort")
    defaultDataLocality: best-effort
    # -- Reclaim policy that provides instructions for handling of a volume after its claim is released. (Options: "Retain", "Delete")
    reclaimPolicy: Delete
    defaultNodeSelector:
      # -- Setting that allows you to enable the node selector for the default Longhorn StorageClass.
      enable: true
      # -- Node selector for the default Longhorn StorageClass. Longhorn uses only nodes with the specified tags for storing volume data. (Examples: "storage,fast")
      selector: "longhorn_storage=true"
    # -- Setting that allows you to specify the data engine version for the default Longhorn StorageClass. (Options: "v1", "v2")
    dataEngine: v2
    # -- Setting that allows you to specify the backup target for the default Longhorn StorageClass.
    backupTargetName: default
  metrics:
    serviceMonitor:
      # -- Setting that allows the creation of a Prometheus ServiceMonitor resource for Longhorn Manager components.
      enabled: true
  service:
    ui:
      annotations:
        omni-kube-service-exposer.sidero.dev/port: "80"
        omni-kube-service-exposer.sidero.dev/label: Longhorn
  preUpgradeChecker:
    jobEnabled: false
