apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.1.8
  - bootstrap-app-set.yaml
  - ingress.yaml

patches:
  - path: config.yaml
  - path: params.yaml
  - path: service.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: ".*"
    path: empty.yaml
